### PR TITLE
Update pug-php version

### PR DESCRIPTION
**Pull request by webdevian**

### CODE REVIEW

**Comment by webdevian** [comment]
Thanks! I've spent all day trying to figure out some pug syntax issues, only to realise they've already been fixed in later versions of pug-php

**Comment by kylekatarnls** [comment]
Thanks to you!

**Comment by webdevian** [comment]
Can you bump the version on this repo too so I can force composer to update both packages

**Comment by webdevian** [comment]
@kylekatarnls Can you create a new release on this repo too so I can force composer to update both packages

**Comment by kylekatarnls** [comment]
Of course, done.

**Pull request merged**
